### ISSUE TITLE
problem to launch osm vnf fortimail

### ISSUE THREAD

**Issue by rohan-kharade** [fortinet-solutions-cse/fortistacks#12]
I am trying to test juju charm. While adding vnfd package fortimail, I am getting following error
I am testing on OSM release four

 {"readyState":4,"responseText":"\"No JSON object could be decoded\"","responseJSON":"No JSON object could be decoded","status":500,"statusText":"Internal Server Error"}

**Comment by thomnico** [comment]
I it is a 2+ years standing issue on Juju actions not accepting json as parameters. Good luck
