### ISSUE TITLE
getting stuck at ./deploy-openstack 

### ISSUE THREAD

**Issue by ghost** [fortinet-solutions-cse/fortistacks#2]
Pls refer to the screen shot attached.

After executing ./deploy-openstack, it downloaded the image but then I got this error.
<img width="1680" alt="error - deploy-openstack" src="https://cloud.githubusercontent.com/assets/2283161/25618616/bcc6514c-2f58-11e7-8489-a57322048aac.png">

**Comment by thomnico** [comment]
There is no image attached

**Comment by ghost** [comment]
Thanks Nicolas for the feedback, the issue was fixed after Hardware virtualization flag on VMware Fusion was enabled. (it was not enabled before).

![mail attachment](https://cloud.githubusercontent.com/assets/2283161/25654760/593f7832-3003-11e7-93a6-3ecd8b12c9fb.png)
