### ISSUE TITLE
fortios_router_bgp

### ISSUE THREAD

**Issue by michaeldoddgit** [fortinet-solutions-cse/fortistacks#22]
In the fortigate debug, when the ansible command fails I see the below, "delete 1"?

0: config vdom
0: edit test
0: config router bgp
0: end
29309 1 cmd =
config vdom
edit test
config router bgp
end
0: end
[httpsd 28636 - 1588373240     info] cmdb_save_with_children[277] -- appended main node (nret=0, is_new=0)
0: config vdom
0: edit test
0: config router bgp
0: config network
0: delete 1
0: end
0: end
29311 1 cmd =
config vdom
edit test
config router bgp
config network
delete 1
end
end
0: end
0: config vdom
0: edit test
29312 1 cmd =
end
0: config router bgp
0: config network
0: edit 0
0: set prefix 1.2.3.0 255.255.255.192
0: end
0: end
29313 1 cmd =
config vdom
edit test
config router bgp
config network
edit 0
set prefix 1.2.3.0 255.255.255.192
end
end
0: end

**Comment by thomnico** [comment]
Hello,

This repository do not deal with Ansible issues, please try  https://galaxy.ansible.com/fortinet/fortios 

Thanks

**Comment by michaeldoddgit** [comment]
Thanks we have shared with our organaizaiton.

--
Thanks,
Mike
